Log cvmfs info
fermitools/jobsub_lite pull request #489
Opened 2023-10-27 23:02 UTC by marcmengel

Addition to standard wrapper to log recent cvmfs info, per #488 . 

Also throwing in an unrelated script I was adding to the testing area for setting up metacat/rucio data files...

2023-10-28 12:48 UTC, shreyb requested changes

2023-10-28 12:48 UTC, shreyb commented on templates/simple/simple.sh
I thought we wanted to log cvmfs lines from failed jobs, not all jobs (referring to SNOW RITM1905386).  

Also, do we have kibana logs from any tests of this new feature?

2023-10-28 12:48 UTC, shreyb commented on tests/job_scripts/rebuild_gen_cfg_metacat
Is this test adding to one of our test scripts?  Where does this get used?  Also, does this add a dependency, or does setting up `hypotcode` do that for us?

2023-10-28 23:55 UTC, marcmengel commented on templates/simple/simple.sh
Well, the feature request was for failed jobs; I thought perhaps doing it for all jobs might be good. 
Because even if the job doesn't FAIL, people might want to know what cvmfs revision the job rand with....

The "example" link in the description should show the test logs in kibana.

2023-10-28 23:59 UTC, marcmengel commented on tests/job_scripts/rebuild_gen_cfg_metacat
I'm planning to add a submission test that does a data-dispatcher get-next-file job, as well as the SAM ones we have now.   This script is  to setup the dataset of files for such a job to read through, much like the one we have there for SAM already. Having it be run is a pre-requisite for adding such a test case; but we don't actually run the SAM one either as part of the tests (although maybe we should)...  So I had it sitting there when I made the branch and thought this was as good a time as any to add it...

2023-10-30 14:50 UTC, shreyb commented on tests/job_scripts/rebuild_gen_cfg_metacat
Fair enough.

2023-10-30 14:56 UTC, shreyb commented on templates/simple/simple.sh
My worry is about this becoming a storage issue on the monitoring side though, if we're sending 50 records from each job.  Otherwise, I agree with you. 

What are your thoughts @retzkek ?

2023-10-30 14:59 UTC, retzkek commented
Before this gets merged I'd like to consider the implications this could have on our logging infrastructure.

2023-10-30 15:27 UTC, marcmengel commented on templates/simple/simple.sh
So far, I've never seen that log request give more than 5 entries.  We could easily set it to limit to 10 or so, I think; we could ping @DrDaveD to see what led him to request 50 initially.

2023-10-30 19:17 UTC, DrDaveD commented on templates/simple/simple.sh
I didn't consider storage issues, but sometimes if there are networking issues it can cycle through a lot of proxies and servers and I figured that up to 50 lines might be interesting.  How about collecting just 5 lines for successful jobs and 50 for failed?  Or if you just want revision number, that can be read instead from the `revision` attribute.

2023-10-30 21:51 UTC, retzkek commented on templates/simple/simple.sh
Looking at the past month, we see about 500K jobs per day, and 20M IFDH messages. So we'd be looking at up to doubling the IFDH log rate and using up to a couple more TiB for 90 days of history. This isn't a deal breaker, it should be manageable, especially if we reduced the retention (90 days does seem a bit much tbh).

@DrDaveD how do you envision this data being used? Do you see value in having logs from multiple machines/sites/jobs together in one place (like Marc's example link)?  What if we only logged the revision with IFDH, but then put the logs into a file in the job sandbox in dCache?

2023-10-30 22:40 UTC, DrDaveD commented on templates/simple/simple.sh
> @DrDaveD how do you envision this data being used? Do you see value in having logs from multiple machines/sites/jobs together in one place (like Marc's example link)?

Yes I do see value in that.  If we have a lot of jobs failing due to cvmfs errors we will want to look at those logs to find out the cause of those failures.

> What if we only logged the revision with IFDH, but then put the logs into a file in the job sandbox in dCache?

I don't understand the implications.  If it's easy enough to look into the cvmfs logs of jobs that fail due to cvmfs errors I'm not sure what difference it makes.

2023-10-31 01:06 UTC, shreyb commented
The only issue I see with sending the cvmfs log to the sandbox is that some
folks (like I believe @DrDaveD) won’t be able to see them without us
downloading them for him.  Otherwise, I think it would work well.

On Mon, Oct 30, 2023 at 5:40 PM DrDaveD ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On templates/simple/simple.sh
> <https://github.com/fermitools/jobsub_lite/pull/489#discussion_r1376872040>
> :
>
> @DrDaveD <https://github.com/DrDaveD> how do you envision this data being
> used? Do you see value in having logs from multiple machines/sites/jobs
> together in one place (like Marc's example link)?
>
> Yes I do see value in that. If we have a lot of jobs failing due to cvmfs
> errors we will want to look at those logs to find out the cause of those
> failures.
>
> What if we only logged the revision with IFDH, but then put the logs into
> a file in the job sandbox in dCache?
>
> I don't understand the implications. If it's easy enough to look into the
> cvmfs logs of jobs that fail due to cvmfs errors I'm not sure what
> difference it makes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fermitools/jobsub_lite/pull/489#discussion_r1376872040>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEWIQ347ZWHPFUNSCQWB52LYCAUE5AVCNFSM6AAAAAA6TO52A6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMBVGE4DEMJUGY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-10-31 16:11 UTC, retzkek commented on templates/simple/simple.sh
OK I'm fine with sending the logs through IFDH.

2023-11-01 15:36 UTC, marcmengel commented on templates/simple/simple.sh
I think so?  So basically full log( max 50 lines ) on failure, last revision num on success?   I think that's pretty easy.

2023-11-02 15:03 UTC, marcmengel commented on templates/simple/simple.sh
That's what I've pushed now.   We log the last cvmfs version line on successful jobs, and all available (up to 50) on failed jobs (exiting non-zero).

2023-11-02 15:06 UTC, shreyb commented on templates/simple/simple.sh
Cool - do you have a test job (maybe one success, one failed) we could take a look at in Kibana to see what this looks like?

2023-11-02 15:07 UTC, shreyb commented on templates/simple/simple.sh
It looks good to me otherwise - but I just want to make sure what we expect is what we actually see.

2023-11-02 15:17 UTC, marcmengel commented on templates/simple/simple.sh
See https://fifemon.fnal.gov/kibana/goto/141c1ddba3bd4eb7f4a06d6f6ba53f1c

2023-11-02 15:19 UTC, marcmengel commented on templates/simple/simple.sh
5806269.0@jobsub04.fnal.gov was a /bin/true job, 5704583.0@jobsub05.fnal.gov was a /bin/false job ("falied")

2023-11-02 15:36 UTC, shreyb commented on templates/simple/simple.sh
Thanks!  Last nitpicky thing here.  Since the record already has the `JobsubJobId`, do we need to repeat that in the log message?  

Instead, what do you think of explicitly stating that the job is completed at the time of the logging?  Something like `"Completed job cvmfs: $line"` (or anything else you think is helpful and brief).

2023-11-02 15:39 UTC, DrDaveD commented
As an optimization, anything that's as old or older than the second-oldest `switched to catalog revision` message could be dropped because it will not be relevant to any cvmfs failure.

2023-11-02 15:44 UTC, shreyb commented
> As an optimization, anything that's as old or older than the second-oldest `switched to catalog revision` message could be dropped because it will not be relevant to any cvmfs failure.

This is a good idea.  I leave it to you, @marcmengel, to decide whether or not to have it go into this PR or split it into another PR/issue/release.

2023-11-06 20:17 UTC, marcmengel commented
Urf.  That took slightly more tries to get right than it should have, but I think this is a good version. 
So we give the last revision update log line if we're successful, but if not, we check if there is more than one
revision update log line, and take everything after the second-to last one if there is; if there are not more than one revision update log line, we take the whole log.

2023-11-07 16:25 UTC, shreyb commented
My good job test looks good (5957618.0@jobsub05.fnal.gov), but my `/bin/false` test (5977824.0@jobsub04.fnal.gov) doesn't show any cvmfs revision lines.  It's possible the job ran for so short that it didn't see any of those.  Let me make a test script that sleeps 5 minutes and then fails, and see if we get better info there.

2023-11-07 16:32 UTC, marcmengel commented
There are some nodes for which that loginfo command returns nothing, but I usually haven't had to run more than 2 submissions to get one with something in the logs.

2023-11-07 16:53 UTC, shreyb commented
Good call on that.  My latest job had that issue.  I'll force `--onsite-only` so that we get an FNAL node for that test.

2023-11-07 17:27 UTC, shreyb commented
Hmm - I'm not able to get the revisions for the failed jobs.  Do you have an example test that you ran?

2023-11-07 17:33 UTC, marcmengel commented
https://landscape.fnal.gov/kibana/goto/271acb0cb3e82133ad201d0dd4c2163d

2023-11-07 17:34 UTC, marcmengel commented
Oh, the other hint is to run -G dune when doing these tests, the fermilab cvmfs is really boring.

2023-11-07 17:36 UTC, marcmengel commented
Also, the stderr from that job is:
```
Mon Nov 6 20:01:10 UTC 2023 5952763.0@jobsub04.fnal.gov BEGIN EXECUTION false
cvmfs info:
Attribute "logbuffer" had a 504 byte value for /cvmfs/dune.opensciencegrid.org/:
[6 Nov 2023 11:52:23 UTC] switching proxy from (none) to http://192.12.238.153:3
128 (set proxies)
[6 Nov 2023 11:52:23 UTC] geographic order of servers retrieved from cvmfs-s1bnl
.opensciencegrid.org
[6 Nov 2023 11:52:23 UTC] switching proxy from http://192.12.238.153:3128 to htt
p://192.12.238.152:3128 (geosort)
[6 Nov 2023 11:52:23 UTC] switching proxy from (none) to http://192.12.238.154:3
128 (cloned)
[6 Nov 2023 11:52:23 UTC] switching proxy from http://192.12.238.154:3128 to DIR
ECT (set proxies)
Mon Nov 6 20:01:11 UTC 2023 false COMPLETED with exit status 1
```

2023-11-08 15:24 UTC, shreyb commented
Alright - then let's go ahead and merge this.

2023-11-08 15:25 UTC, merged